[package]
name = "swm_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
# clap = "4.6.1"
const_env = "0.1.5"
csv = "1.4.0"
ndarray = { version = "0.17.2", optional = true }
mdarray = { version = "0.8.0", optional = true }

[features]
box    = []
vec    = []
ndarray = ["dep:ndarray"]
mdarray = ["dep:mdarray"]

[[bin]]
name = "swm_rust"
path = "src/swm_rust.rs"
